# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osi', '0002_auto_20190218_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='reparticion',
            field=models.CharField(choices=[('paipote', 'paipote'), ('b', 'NN'), ('c', 'antofagasta'), ('d', 'rancagua'), ('e', 'santiago'), ('f', 'coquimbo'), ('g', 'amalia'), ('h', 'arica'), ('i', 'barriles'), ('j', 'cabildo'), ('k', 'calama'), ('l', 'camarones'), ('m', 'catemu'), ('n', 'copiapo'), ('o', 'delta'), ('p', 'el arenal'), ('q', 'el salado'), ('r', 'illapel'), ('s', 'la serena'), ('t', 'las cenizas'), ('u', 'las luces'), ('v', 'mantos blancos'), ('w', 'matta'), ('x', 'ovalle'), ('y', 'panulcillo'), ('z', 'rumano chileno'), ('ab', 'taltal'), ('ac', 'tocopilla'), ('ad', 'vallenar'), ('ae', 'ventanas')], default='paipote', max_length=1),
        ),
    ]
